import { api } from "../utils/api.js";

/**
 * Fetch paginated queries for a specific file.
 *
 * @param {string} fileId  – UUID of the file
 * @param {number} [page=1]
 * @param {number} [limit=10]
 * @returns {{ summary, queries }}
 */
export const getQueriesByFile = async (fileId, page = 1, limit = 10) => {
  const res = await api.get(`/files/${fileId}/queries`, {
    params: { page, limit },
  });
  return res.data.data;
};

/**
 * Fetch full details of a single query.
 *
 * @param {string} queryId – UUID of the query
 * @returns {{ id, queryNumber, title, description, priority, status, dueDate, createdAt, resolvedAt, resolutionText, daysTaken, file, raisedBy, assignedTo, resolvedBy, attachments }}
 */
export const getQueryDetail = async (queryId) => {
  const res = await api.get(`/queries/${queryId}`);
  return res.data.data;
};

/**
 * Fetch cursor-paginated replies for a query.
 *
 * @param {string} queryId
 * @param {number} [limit=10]
 * @param {string|null} [cursor=null] – pass nextCursor from previous response
 * @returns {{ replies, pagination: { hasMore, nextCursor } }}
 */
export const getQueryReplies = async (queryId, limit = 10, cursor = null) => {
  const params = { limit };
  if (cursor) params.cursor = cursor;
  const res = await api.get(`/queries/${queryId}/replies`, { params });
  return res.data.data;
};

/**
 * Fetch participants of a query.
 *
 * @param {string} queryId
 * @returns {{ participants: [{ id, userId, name, roleName, addedAt }] }}
 */
export const getQueryParticipants = async (queryId) => {
  const res = await api.get(`/queries/${queryId}/participants`);
  return res.data.data;
};

/**
 * Fetch the full activity log for a query.
 *
 * @param {string} queryId
 * @returns {{ activityLog: [{ id, actionType, detail, performedAt, actor }] }}
 */
export const getQueryActivityLog = async (queryId) => {
  const res = await api.get(`/queries/${queryId}/activity-log`);
  return res.data.data;
};

/**
 * Fetch users who can be assigned to a query on a given file.
 *
 * @param {string} fileId
 * @returns {{ assignableUsers: [{ userId, name, roleName }] }}
 */
export const getAssignableUsers = async (fileId) => {
  const res = await api.get(`/files/${fileId}/assignable-users`);
  return res.data.data;
};

/**
 * Create a new query on a file.
 *
 * @param {string} fileId
 * @param {{ title, description, assignedTo, priority, dueDate, checklistId, userId }} payload
 * @returns {{ id, queryNumber, fileId, title, description, priority, status, raisedBy, assignedTo, dueDate, checklistId, autoGenerated, createdAt }}
 */
export const createQuery = async (fileId, payload) => {
  const res = await api.post(`/files/${fileId}/queries`, payload);
  return res.data.data;
};

/**
 * Upload document attachments to an existing query (multipart).
 *
 * @param {string} queryId
 * @param {File[]} files – raw File objects from input
 * @returns {Array<{ id, queryId, fileName, fileSize, mimeType, storagePath, storageBackend, uploadedBy, uploadedAt }>}
 */
export const uploadQueryAttachments = async (queryId, files) => {
  const formData = new FormData();
  files.forEach((f) => formData.append("documents", f));
  const res = await api.post(`/queries/${queryId}/attachments`, formData, {
    headers: { "Content-Type": "multipart/form-data" },
  });
  return res.data.data;
};

/**
 * Post a reply to a query with optional file attachments (multipart).
 *
 * @param {string} queryId
 * @param {string} replyText
 * @param {File[]} [files=[]] – raw File objects
 * @returns {{ id, replyText, repliedAt, repliedBy, attachments, statusTransition }}
 */
export const createReply = async (queryId, replyText, files = []) => {
  const formData = new FormData();
  formData.append("replyText", replyText);
  files.forEach((f) => formData.append("documents", f));
  const res = await api.post(`/queries/${queryId}/replies`, formData, {
    headers: { "Content-Type": "multipart/form-data" },
  });
  return res.data.data;
};

/**
 * Mark a query as resolved with mandatory resolution text.
 *
 * @param {string} queryId
 * @param {string} resolutionText
 * @returns {{ id, status, resolvedAt, resolvedBy, resolutionText, daysTaken }}
 */
export const resolveQuery = async (queryId, resolutionText) => {
  const res = await api.patch(`/queries/${queryId}/resolve`, { resolutionText });
  return res.data.data;
};

/**
 * Fetch users eligible to be added as participants to a query.
 *
 * @param {string} queryId
 * @returns {{ eligibleParticipants: [{ userId, name, roleName }] }}
 */
export const getEligibleParticipants = async (queryId) => {
  const res = await api.get(`/queries/${queryId}/eligible-participants`);
  return res.data.data;
};

/**
 * Add a user as a participant to a query.
 *
 * @param {string} queryId
 * @param {string} participantUserId – the user being added
 * @returns {{ id, userId, name, roleName, addedAt }}
 */
export const addQueryParticipant = async (queryId, participantUserId) => {
  const res = await api.post(`/queries/${queryId}/participants`, {
    participantUserId,
  });
  return res.data.data;
};

/**
 * Get a time-limited signed download URL for a query attachment.
 *
 * @param {string} attachmentId
 * @returns {{ id, fileName, mimeType, fileSize, downloadUrl, expiresIn }}
 */
export const downloadQueryAttachment = async (attachmentId) => {
  const res = await api.get(`/query-attachments/${attachmentId}/download`);
  return res.data.data;
};