export const DUMMY_TEAM_MEMBERS = [
  { id: "u1", name: "Arvind Mehta",    role: "Partner" },
  { id: "u2", name: "Priya Sharma",    role: "State Controller" },
  { id: "u3", name: "Vikram Singh",    role: "Team Lead" },
  { id: "u4", name: "Muskan Agarwal",  role: "Chartered Accountant" },
  { id: "u5", name: "Shikha Verma",    role: "ULB Field Executive" },
  { id: "u6", name: "Rajan Tiwari",    role: "Non-ULB Field Executive" },
];

export const DUMMY_ALLOCATION_USERS = [
  {
    id: "u3",  name: "Vikram Singh",   role: "Team Lead",
    district: "Raipur",      city: "Raipur",      phone: "+91 98100 11001",
    availability: "Available",
    experienceYears: 7,  auditedULBsTotal: 18,
    completionRate: 92,  avgResolutionDays: 4,
    hasOwnTransport: true,
    previousULBIds: ["ulb1", "ulb3", "ulb5"],
    specializations: ["Roads", "Financial Audit"],
  },
  {
    id: "u7",  name: "Anita Rao",      role: "Team Lead",
    district: "Bilaspur",    city: "Bilaspur",    phone: "+91 98100 11002",
    availability: "Occupied",
    experienceYears: 5,  auditedULBsTotal: 12,
    completionRate: 85,  avgResolutionDays: 5,
    hasOwnTransport: true,
    previousULBIds: ["ulb2", "ulb4"],
    specializations: ["Water Supply", "Infrastructure"],
  },
  {
    id: "u8",  name: "Deepak Nair",    role: "Team Lead",
    district: "Durg",        city: "Bhilai",      phone: "+91 98100 11003",
    availability: "Available",
    experienceYears: 6,  auditedULBsTotal: 15,
    completionRate: 88,  avgResolutionDays: 4,
    hasOwnTransport: true,
    previousULBIds: ["ulb3", "ulb9"],
    specializations: ["Roads", "Drainage"],
  },
  {
    id: "u4",  name: "Muskan Agarwal", role: "Chartered Accountant",
    district: "Raipur",      city: "Raipur",      phone: "+91 98100 22001",
    availability: "Available",
    experienceYears: 4,  auditedULBsTotal: 9,
    completionRate: 90,  avgResolutionDays: 3,
    hasOwnTransport: false,
    previousULBIds: ["ulb1", "ulb2"],
    specializations: ["Financial Audit", "TDS Compliance"],
  },
  {
    id: "u9",  name: "Rohit Gupta",    role: "Chartered Accountant",
    district: "Korba",       city: "Korba",       phone: "+91 98100 22002",
    availability: "On Leave",
    experienceYears: 3,  auditedULBsTotal: 7,
    completionRate: 75,  avgResolutionDays: 6,
    hasOwnTransport: true,
    previousULBIds: ["ulb5"],
    specializations: ["Financial Audit"],
  },
  {
    id: "u10", name: "Preethi Shenoy", role: "Chartered Accountant",
    district: "Bilaspur",    city: "Bilaspur",    phone: "+91 98100 22003",
    availability: "Available",
    experienceYears: 5,  auditedULBsTotal: 11,
    completionRate: 82,  avgResolutionDays: 4,
    hasOwnTransport: false,
    previousULBIds: ["ulb2", "ulb7"],
    specializations: ["Financial Audit", "Labour Compliance"],
  },
  {
    id: "u5",  name: "Shikha Verma",   role: "ULB Field Executive",
    district: "Raipur",      city: "Raipur",      phone: "+91 98100 33001",
    availability: "Occupied",
    experienceYears: 3,  auditedULBsTotal: 8,
    completionRate: 78,  avgResolutionDays: 5,
    hasOwnTransport: false,
    previousULBIds: ["ulb1"],
    specializations: ["Site Inspection", "Measurement"],
  },
  {
    id: "u11", name: "Manish Tiwari",  role: "ULB Field Executive",
    district: "Bastar",      city: "Jagdalpur",   phone: "+91 98100 33002",
    availability: "Available",
    experienceYears: 4,  auditedULBsTotal: 10,
    completionRate: 84,  avgResolutionDays: 4,
    hasOwnTransport: true,
    previousULBIds: ["ulb4", "ulb6"],
    specializations: ["Roads", "Site Inspection"],
  },
  {
    id: "u12", name: "Kavita Bhatt",   role: "ULB Field Executive",
    district: "Raigarh",     city: "Raigarh",     phone: "+91 98100 33003",
    availability: "Available",
    experienceYears: 2,  auditedULBsTotal: 5,
    completionRate: 72,  avgResolutionDays: 7,
    hasOwnTransport: true,
    previousULBIds: ["ulb8"],
    specializations: ["Site Inspection"],
  },
  {
    id: "u6",  name: "Rajan Tiwari",   role: "Non-ULB Field Executive",
    district: "Raipur",      city: "Raipur",      phone: "+91 98100 44001",
    availability: "Available",
    experienceYears: 4,  auditedULBsTotal: 11,
    completionRate: 80,  avgResolutionDays: 5,
    hasOwnTransport: true,
    previousULBIds: ["ulb1", "ulb3"],
    specializations: ["Measurement", "Infrastructure"],
  },
  {
    id: "u13", name: "Suresh Patel",   role: "Non-ULB Field Executive",
    district: "Surguja",     city: "Ambikapur",   phone: "+91 98100 44002",
    availability: "Available",
    experienceYears: 3,  auditedULBsTotal: 7,
    completionRate: 76,  avgResolutionDays: 6,
    hasOwnTransport: true,
    previousULBIds: ["ulb7"],
    specializations: ["Roads"],
  },
  {
    id: "u14", name: "Meena Joshi",    role: "Non-ULB Field Executive",
    district: "Rajnandgaon", city: "Rajnandgaon", phone: "+91 98100 44003",
    availability: "On Leave",
    experienceYears: 2,  auditedULBsTotal: 4,
    completionRate: 70,  avgResolutionDays: 8,
    hasOwnTransport: false,
    previousULBIds: ["ulb6"],
    specializations: ["Site Inspection"],
  },
];

export const DUMMY_ULBS = [
  { id: "ulb1",  name: "Raipur Municipal Corporation",       district: "Raipur",       type: "Municipal Corporation" },
  { id: "ulb2",  name: "Bilaspur Municipal Corporation",     district: "Bilaspur",     type: "Municipal Corporation" },
  { id: "ulb3",  name: "Durg Municipal Corporation",         district: "Durg",         type: "Municipal Corporation" },
  { id: "ulb4",  name: "Jagdalpur Municipal Council",        district: "Bastar",       type: "Municipal Council" },
  { id: "ulb5",  name: "Korba Municipal Corporation",        district: "Korba",        type: "Municipal Corporation" },
  { id: "ulb6",  name: "Rajnandgaon Municipal Council",      district: "Rajnandgaon",  type: "Municipal Council" },
  { id: "ulb7",  name: "Ambikapur Municipal Corporation",    district: "Surguja",      type: "Municipal Corporation" },
  { id: "ulb8",  name: "Raigarh Municipal Corporation",      district: "Raigarh",      type: "Municipal Corporation" },
  { id: "ulb9",  name: "Bhilai Nagar Municipal Corporation", district: "Durg",         type: "Municipal Corporation" },
  { id: "ulb10", name: "Chirmiri Municipal Council",         district: "Korea",        type: "Municipal Council" },
];

export const DUMMY_TEAMS = [
  {
    id: "t1",
    name: "Team Alpha",
    members: [
      { id: "u3",  name: "Vikram Singh",   role: "Team Lead" },
      { id: "u4",  name: "Muskan Agarwal", role: "Chartered Accountant" },
      { id: "u5",  name: "Shikha Verma",   role: "ULB Field Executive" },
      { id: "u6",  name: "Rajan Tiwari",   role: "Non-ULB Field Executive" },
    ],
    createdOn: "01/01/2026",
  },
  {
    id: "t2",
    name: "Team Beta",
    members: [
      { id: "u7",  name: "Anita Rao",      role: "Team Lead" },
      { id: "u9",  name: "Rohit Gupta",    role: "Chartered Accountant" },
      { id: "u11", name: "Manish Tiwari",  role: "ULB Field Executive" },
    ],
    createdOn: "15/01/2026",
  },
  {
    id: "t3",
    name: "Team Gamma",
    members: [
      { id: "u8",  name: "Deepak Nair",    role: "Team Lead" },
      { id: "u10", name: "Preethi Shenoy", role: "Chartered Accountant" },
      { id: "u12", name: "Kavita Bhatt",   role: "ULB Field Executive" },
      { id: "u13", name: "Suresh Patel",   role: "Non-ULB Field Executive" },
    ],
    createdOn: "20/01/2026",
  },
];

export const DUMMY_ULB_ASSIGNMENTS = {
  ulb1: { teams: ["t1"], individuals: [] },
  ulb2: { teams: [], individuals: [{ id: "u9", name: "Rohit Gupta", role: "Chartered Accountant" }] },
  ulb3: { teams: ["t2"], individuals: [] },
};

export const DUMMY_FILES = [
  // ── Raipur Municipal Corporation (ulb1) ── Team Alpha (t1): u3 u4 u5 u6
  {
    fileNumber: "RMC/2024/WRK/0008",
    fileTitle: "Water Supply Pipeline Rehabilitation",
    ulb: "Raipur Municipal Corporation",
    workDescription: "Rehabilitation of 12 km water supply pipeline in Zone 3",
    amount: 850000,
    riskFlag: "Low",
    contractType: "Works",
    status: "Finalized",
    date: "08/03/2026",
    attachmentCount: 0,
    finalized: true,
    finalizedAt: "10/03/2026",
    finalizedBy: "CA Sharma",
    deniedAccess: { userIds: [], teamIds: [] },
    masterData: { supplierName: "", pan: "", gstNumber: "", epfRegNo: "", esicRegNo: "", labourLicenseNo: "", nameOfDepartment: "", fileNo: "", nameOfFund: "" },
    checklists: [{ id: "CHK-001", phase: 1, checkerName: "", date: "", createdAt: "", createdBy: "", versionHistory: [] }],
  },
  {
    fileNumber: "RMC/2024/WRK/0011",
    fileTitle: "Road Repair Contract — Main Bazar to Station Road",
    ulb: "Raipur Municipal Corporation",
    workDescription: "Repair and resurfacing of 3.2 km stretch from Main Bazar to Station Road",
    amount: 1200000,
    riskFlag: "Medium",
    contractType: "Works",
    status: "Pre-Audit",
    date: "02/03/2026",
    attachmentCount: 3,
    finalized: false,
    deniedAccess: { userIds: [], teamIds: [] },
    masterData: { supplierName: "", pan: "", gstNumber: "", epfRegNo: "", esicRegNo: "", labourLicenseNo: "", nameOfDepartment: "", fileNo: "", nameOfFund: "" },
    checklists: [{ id: "CHK-001", phase: 1, checkerName: "", date: "", createdAt: "", createdBy: "", versionHistory: [] }],
  },
  {
    fileNumber: "RMC/2025/SUP/0003",
    fileTitle: "Street Light Material Procurement — Phase 1",
    ulb: "Raipur Municipal Corporation",
    workDescription: "Procurement of 400 LED street light units for Zone 1 and Zone 2",
    amount: 560000,
    riskFlag: "Low",
    contractType: "Supply",
    status: "Under Review",
    date: "05/03/2026",
    attachmentCount: 2,
    finalized: false,
    deniedAccess: { userIds: [], teamIds: [] },
    masterData: { supplierName: "", pan: "", gstNumber: "", epfRegNo: "", esicRegNo: "", labourLicenseNo: "", nameOfDepartment: "", fileNo: "", nameOfFund: "" },
    checklists: [{ id: "CHK-001", phase: 1, checkerName: "", date: "", createdAt: "", createdBy: "", versionHistory: [] }],
  },
  {
    fileNumber: "RMC/2025/SRV/0015",
    fileTitle: "Sanitation Services Contract — Ward 7 to 12",
    ulb: "Raipur Municipal Corporation",
    workDescription: "Annual sanitation and waste collection services for wards 7 through 12",
    amount: 980000,
    riskFlag: "High",
    contractType: "Service",
    status: "Pre-Audit",
    date: "01/03/2026",
    attachmentCount: 1,
    finalized: false,
    deniedAccess: { userIds: [], teamIds: [] },
    masterData: { supplierName: "", pan: "", gstNumber: "", epfRegNo: "", esicRegNo: "", labourLicenseNo: "", nameOfDepartment: "", fileNo: "", nameOfFund: "" },
    checklists: [{ id: "CHK-001", phase: 1, checkerName: "", date: "", createdAt: "", createdBy: "", versionHistory: [] }],
  },
  // ── Bilaspur Municipal Corporation (ulb2) ── Individual: Rohit Gupta (u9)
  {
    fileNumber: "BMC/2024/SUP/0022",
    fileTitle: "Office Supply Purchase — Zone 2 Administrative Block",
    ulb: "Bilaspur Municipal Corporation",
    workDescription: "Purchase of office supplies and stationery for Zone 2 administrative block",
    amount: 145000,
    riskFlag: "Low",
    contractType: "Supply",
    status: "Post-Audit",
    date: "01/03/2026",
    attachmentCount: 2,
    finalized: false,
    deniedAccess: { userIds: [], teamIds: [] },
    masterData: { supplierName: "", pan: "", gstNumber: "", epfRegNo: "", esicRegNo: "", labourLicenseNo: "", nameOfDepartment: "", fileNo: "", nameOfFund: "" },
    checklists: [{ id: "CHK-001", phase: 1, checkerName: "", date: "", createdAt: "", createdBy: "", versionHistory: [] }],
  },
  {
    fileNumber: "BMC/2025/WRK/0009",
    fileTitle: "Drainage Canal Repair — North Zone",
    ulb: "Bilaspur Municipal Corporation",
    workDescription: "Desilting and structural repair of 5 km drainage canal in North Zone",
    amount: 720000,
    riskFlag: "Medium",
    contractType: "Works",
    status: "Pre-Audit",
    date: "06/03/2026",
    attachmentCount: 0,
    finalized: false,
    deniedAccess: { userIds: [], teamIds: [] },
    masterData: { supplierName: "", pan: "", gstNumber: "", epfRegNo: "", esicRegNo: "", labourLicenseNo: "", nameOfDepartment: "", fileNo: "", nameOfFund: "" },
    checklists: [{ id: "CHK-001", phase: 1, checkerName: "", date: "", createdAt: "", createdBy: "", versionHistory: [] }],
  },
  // ── Durg Municipal Corporation (ulb3) ── Team Beta (t2): u7 u9 u11
  {
    fileNumber: "DMC/2025/WRK/0017",
    fileTitle: "Road Resurfacing — Industrial Zone Connector",
    ulb: "Durg Municipal Corporation",
    workDescription: "Resurfacing of 4.5 km road connecting industrial zone to main highway",
    amount: 1650000,
    riskFlag: "High",
    contractType: "Works",
    status: "Pre-Audit",
    date: "04/03/2026",
    attachmentCount: 4,
    finalized: false,
    deniedAccess: { userIds: [], teamIds: [] },
    masterData: { supplierName: "", pan: "", gstNumber: "", epfRegNo: "", esicRegNo: "", labourLicenseNo: "", nameOfDepartment: "", fileNo: "", nameOfFund: "" },
    checklists: [{ id: "CHK-001", phase: 1, checkerName: "", date: "", createdAt: "", createdBy: "", versionHistory: [] }],
  },
  {
    fileNumber: "DMC/2025/CON/0005",
    fileTitle: "Technical Consultancy for Urban Master Plan",
    ulb: "Durg Municipal Corporation",
    workDescription: "Consultancy services for preparation of urban master plan 2031",
    amount: 430000,
    riskFlag: "Low",
    contractType: "Consultancy",
    status: "Indexed",
    date: "10/02/2026",
    attachmentCount: 5,
    finalized: false,
    deniedAccess: { userIds: [], teamIds: [] },
    masterData: { supplierName: "", pan: "", gstNumber: "", epfRegNo: "", esicRegNo: "", labourLicenseNo: "", nameOfDepartment: "", fileNo: "", nameOfFund: "" },
    checklists: [{ id: "CHK-001", phase: 1, checkerName: "", date: "", createdAt: "", createdBy: "", versionHistory: [] }],
  },
  // ── Raipur Municipal Corporation (ulb1) — Manpower Service demo file
  {
    fileNumber: "RMC/2025/MPS/0001",
    fileTitle: "Manpower Supply Services — Sanitation & Sweeping Staff",
    ulb: "Raipur Municipal Corporation",
    workDescription: "Supply of sanitation and sweeping staff for Zones 4–6 under annual manpower contract",
    amount: 760000,
    riskFlag: "Medium",
    contractType: "Manpower Service",
    status: "Pre-Audit",
    date: "10/03/2026",
    attachmentCount: 2,
    finalized: false,
    checklistType: "manpower",
    deniedAccess: { userIds: [], teamIds: [] },
    checklists: [
      {
        id: "CHK-001",
        phase: 1,
        checkerName: "Muskan Agarwal",
        date: "2026-03-10",
        createdAt: "10/03/2026",
        createdBy: "Muskan Agarwal",
        versionHistory: [
          { savedAt: "10/03/2026 11:00 AM", savedBy: "Muskan Agarwal", userRole: "Chartered Accountant" },
        ],
      },
    ],
    masterData: {
      supplierName: "Shree Balaji Manpower Services",
      pan: "AABCS1429B",
      gstNumber: "22AABCS1429B1ZT",
      epfRegNo: "MP/BLS/0012345",
      esicRegNo: "31-00-123456-000-0001",
      labourLicenseNo: "LL/RMC/2024/0098",
      nameOfDepartment: "Municipal Services",
      fileNo: "RMC/2025/MPS/0001",
      nameOfFund: "XIV Finance Commission",
    },
  },
];

export const DUMMY_QUERIES = [
  {
    id: "QRY-001",
    fileNumber: "RMC/2024/WRK/0008",
    fileTitle: "Water Supply Pipeline Rehabilitation — Phase 2",
    ulb: "Raipur Municipal Corporation",
    title: "TDS deduction certificate missing for challan #TDS/24-25/0118",
    description:
      "The TDS certificate for challan no. TDS/24-25/0118 has not been uploaded against this work order. As per audit protocol, this document is mandatory before the payment voucher can be certified. Please provide the original document scanned at minimum 300 DPI in PDF format.",
    priority: "High",
    status: "Open",
    raisedBy: { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
    assignedTo: { id: "u5", name: "Shikha Verma", role: "ULB Field Executive" },
    participants: [
      { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
      { id: "u5", name: "Shikha Verma",   role: "ULB Field Executive" },
      { id: "u3", name: "Vikram Singh",   role: "Team Lead" },
    ],
    createdAt: "05/03/2026",
    dueDate: "12/03/2026",
    resolvedAt: null,
    daysTaken: null,
    attachments: [
      { name: "query_notice_ref.pdf", size: "24 KB", ext: "pdf" },
    ],
    replies: [
      {
        id: "r1",
        author: { id: "u5", name: "Shikha Verma", role: "ULB Field Executive" },
        message:
          "I have escalated this with the contractor's accounts team. They have confirmed the TDS payment was made and will submit a copy of the challan by 10th March.",
        createdAt: "06/03/2026 11:42 AM",
        attachments: [],
      },
      {
        id: "r2",
        author: { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
        message:
          "Noted. Please ensure the scanned copy is legible. The earlier submission for another challan was blurry and had to be rejected. Also looping in Vikram Singh for awareness.",
        createdAt: "07/03/2026 09:15 AM",
        attachments: [
          { name: "scan_quality_guidelines.pdf", size: "12 KB", ext: "pdf" },
        ],
      },
      {
        id: "r3",
        author: { id: "u3", name: "Vikram Singh", role: "Team Lead" },
        message:
          "Thanks for the loop-in. Shikha, please also check if there are any other pending TDS challans for this file while you're at it. We want to clear all outstanding items in one go.",
        createdAt: "07/03/2026 10:30 AM",
        attachments: [],
      },
    ],
    activityLog: [
      { id: "a1", type: "created",     actor: "Muskan Agarwal", at: "05/03/2026 10:00 AM", detail: null },
      { id: "a2", type: "assigned",    actor: "Muskan Agarwal", at: "05/03/2026 10:01 AM", detail: "Assigned to Shikha Verma" },
      { id: "a3", type: "replied",     actor: "Shikha Verma",   at: "06/03/2026 11:42 AM", detail: null },
      { id: "a4", type: "replied",     actor: "Muskan Agarwal", at: "07/03/2026 09:15 AM", detail: "Attached: scan_quality_guidelines.pdf" },
      { id: "a5", type: "participant", actor: "Muskan Agarwal", at: "07/03/2026 09:16 AM", detail: "Added Vikram Singh as participant" },
      { id: "a6", type: "replied",     actor: "Vikram Singh",   at: "07/03/2026 10:30 AM", detail: null },
    ],
  },

  {
    id: "QRY-002",
    fileNumber: "RMC/2024/WRK/0008",
    fileTitle: "Water Supply Pipeline Rehabilitation — Phase 2",
    ulb: "Raipur Municipal Corporation",
    title: "Labour cess compliance certificate not submitted by contractor",
    description:
      "The contractor has not submitted the labour cess compliance certificate as required under the Building & Other Construction Workers Act. Non-compliance blocks file finalization. The due date for this submission was 28/02/2026. Please coordinate with the contractor and upload the certificate at the earliest.",
    priority: "Medium",
    status: "In Progress",
    raisedBy: { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
    assignedTo: { id: "u3", name: "Vikram Singh",  role: "Team Lead" },
    participants: [
      { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
      { id: "u3", name: "Vikram Singh",   role: "Team Lead" },
    ],
    createdAt: "28/02/2026",
    dueDate: "15/03/2026",
    resolvedAt: null,
    daysTaken: null,
    attachments: [],
    replies: [
      {
        id: "r1",
        author: { id: "u3", name: "Vikram Singh", role: "Team Lead" },
        message:
          "I have contacted the contractor's site engineer. They are arranging the certificate from their head office. Expecting it by 13th March.",
        createdAt: "03/03/2026 03:20 PM",
        attachments: [],
      },
    ],
    activityLog: [
      { id: "a1", type: "created",  actor: "Muskan Agarwal", at: "28/02/2026 02:00 PM", detail: null },
      { id: "a2", type: "assigned", actor: "Muskan Agarwal", at: "28/02/2026 02:01 PM", detail: "Assigned to Vikram Singh" },
      { id: "a3", type: "status",   actor: "Vikram Singh",   at: "01/03/2026 10:00 AM", detail: "Status changed to In Progress" },
      { id: "a4", type: "replied",  actor: "Vikram Singh",   at: "03/03/2026 03:20 PM", detail: null },
    ],
  },

  {
    id: "QRY-003",
    fileNumber: "BMC/2024/SUP/0022",
    fileTitle: "Office Supply Purchase — Zone 2 Administrative Block",
    ulb: "Bilaspur Municipal Corporation",
    title: "Comparative statement lacks counter-signature from competent authority",
    description:
      "The comparative statement on file (page 14-15) is missing the counter-signature from the competent authority (Deputy Commissioner rank or above). This is a mandatory requirement under GFR Rule 147. The document was accepted for audit purposes but cannot be certified without this signature. Please get it signed and re-upload.",
    priority: "Low",
    status: "Resolved",
    raisedBy: { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
    assignedTo: { id: "u2", name: "Priya Sharma",  role: "State Controller" },
    participants: [
      { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
      { id: "u2", name: "Priya Sharma",   role: "State Controller" },
    ],
    createdAt: "01/03/2026",
    dueDate: "07/03/2026",
    resolvedAt: "06/03/2026 04:30 PM",
    daysTaken: 5,
    attachments: [],
    replies: [
      {
        id: "r1",
        author: { id: "u2", name: "Priya Sharma", role: "State Controller" },
        message:
          "Obtained the counter-signature from DC office today. Uploading the re-signed comparative statement. Please confirm once you have reviewed it.",
        createdAt: "06/03/2026 04:25 PM",
        attachments: [
          { name: "comparative_statement_signed_v2.pdf", size: "156 KB", ext: "pdf" },
        ],
      },
      {
        id: "r2",
        author: { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
        message:
          "Reviewed and confirmed. The signature is in order. Marking this query as resolved.",
        createdAt: "06/03/2026 04:30 PM",
        attachments: [],
      },
    ],
    activityLog: [
      { id: "a1", type: "created",  actor: "Muskan Agarwal", at: "01/03/2026 09:00 AM", detail: null },
      { id: "a2", type: "assigned", actor: "Muskan Agarwal", at: "01/03/2026 09:01 AM", detail: "Assigned to Priya Sharma" },
      { id: "a3", type: "replied",  actor: "Priya Sharma",   at: "06/03/2026 04:25 PM", detail: "Attached: comparative_statement_signed_v2.pdf" },
      { id: "a4", type: "replied",  actor: "Muskan Agarwal", at: "06/03/2026 04:30 PM", detail: null },
      { id: "a5", type: "resolved", actor: "Muskan Agarwal", at: "06/03/2026 04:30 PM", detail: "Marked resolved. Days taken: 5" },
    ],
  },

  {
    id: "QRY-004",
    fileNumber: "JMC/2025/INF/0041",
    fileTitle: "Road Resurfacing — NH Connector Stretch B",
    ulb: "Jagdalpur Municipal Council",
    title: "Measurement book entries do not match final bill quantities",
    description:
      "On cross-referencing the measurement book (MB No. JMC/MB/2025/089) with the final bill submitted by the contractor, discrepancies have been found in the quantities for items 3(b), 5, and 7(a). The variation exceeds the permissible 5% threshold. Please provide a reconciliation statement with justification for the variation, along with the site engineer's certification.",
    priority: "High",
    status: "Open",
    raisedBy: { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
    assignedTo: { id: "u6", name: "Rajan Tiwari",  role: "Non-ULB Field Executive" },
    participants: [
      { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
      { id: "u6", name: "Rajan Tiwari",   role: "Non-ULB Field Executive" },
    ],
    createdAt: "09/03/2026",
    dueDate: "16/03/2026",
    resolvedAt: null,
    daysTaken: null,
    attachments: [
      { name: "discrepancy_matrix.xlsx", size: "38 KB", ext: "xlsx" },
      { name: "mb_extract_pages_12_15.pdf", size: "210 KB", ext: "pdf" },
    ],
    replies: [],
    activityLog: [
      { id: "a1", type: "created",  actor: "Muskan Agarwal", at: "09/03/2026 11:00 AM", detail: null },
      { id: "a2", type: "assigned", actor: "Muskan Agarwal", at: "09/03/2026 11:01 AM", detail: "Assigned to Rajan Tiwari" },
    ],
  },

  // ── Queries for RMC/2024/WRK/0011 — Road Repair Contract (visible to Rajan Tiwari via Team Alpha / ulb1)
  {
    id: "QRY-005",
    fileNumber: "RMC/2024/WRK/0011",
    fileTitle: "Road Repair Contract — Main Bazar to Station Road",
    ulb: "Raipur Municipal Corporation",
    title: "Site photographs for completed stretch not uploaded",
    description:
      "As per the audit protocol, geo-tagged site photographs must be uploaded at each 500 m interval for road repair works. For the stretch from Main Bazar Chowk to Railway Station Road (chainage 0–1.8 km), no photographs have been submitted. Please capture and upload geotagged photographs at the required intervals as per the field documentation checklist.",
    priority: "High",
    status: "Open",
    raisedBy: { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
    assignedTo: { id: "u6", name: "Rajan Tiwari", role: "Non-ULB Field Executive" },
    participants: [
      { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
      { id: "u6", name: "Rajan Tiwari",   role: "Non-ULB Field Executive" },
      { id: "u3", name: "Vikram Singh",   role: "Team Lead" },
    ],
    createdAt: "07/03/2026",
    dueDate: "14/03/2026",
    resolvedAt: null,
    daysTaken: null,
    attachments: [
      { name: "photo_upload_checklist.pdf", size: "18 KB", ext: "pdf" },
    ],
    replies: [
      {
        id: "r1",
        author: { id: "u6", name: "Rajan Tiwari", role: "Non-ULB Field Executive" },
        message:
          "I visited the site on 8th March. The contractor's team was resurfacing that stretch so photographs could not be taken safely. Site will be accessible by 10th March. I will upload all required geotagged photos by 11th March.",
        createdAt: "08/03/2026 05:10 PM",
        attachments: [],
      },
      {
        id: "r2",
        author: { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
        message:
          "Understood. Please ensure the photos clearly show the road surface, chainage markers, and date-time metadata. Looping in Vikram Singh for awareness.",
        createdAt: "09/03/2026 10:00 AM",
        attachments: [],
      },
      {
        id: "r3",
        author: { id: "u3", name: "Vikram Singh", role: "Team Lead" },
        message:
          "Rajan, please also capture photographs at the drainage side drains alongside this stretch — those were flagged in last year's audit as well.",
        createdAt: "09/03/2026 11:30 AM",
        attachments: [],
      },
    ],
    activityLog: [
      { id: "a1", type: "created",     actor: "Muskan Agarwal", at: "07/03/2026 09:30 AM", detail: null },
      { id: "a2", type: "assigned",    actor: "Muskan Agarwal", at: "07/03/2026 09:31 AM", detail: "Assigned to Rajan Tiwari" },
      { id: "a3", type: "replied",     actor: "Rajan Tiwari",   at: "08/03/2026 05:10 PM", detail: null },
      { id: "a4", type: "replied",     actor: "Muskan Agarwal", at: "09/03/2026 10:00 AM", detail: null },
      { id: "a5", type: "participant", actor: "Muskan Agarwal", at: "09/03/2026 10:01 AM", detail: "Added Vikram Singh as participant" },
      { id: "a6", type: "replied",     actor: "Vikram Singh",   at: "09/03/2026 11:30 AM", detail: null },
    ],
  },

  {
    id: "QRY-006",
    fileNumber: "RMC/2024/WRK/0011",
    fileTitle: "Road Repair Contract — Main Bazar to Station Road",
    ulb: "Raipur Municipal Corporation",
    title: "Joint measurement sheet not signed by ULB representative",
    description:
      "The joint measurement sheet (JMS dated 25/02/2026) submitted for the Station Road stretch is signed only by the contractor's site supervisor. The counter-signature of the ULB's Junior Engineer or above is mandatory before payment certification. Please arrange for the JMS to be counter-signed and re-submit the document.",
    priority: "Medium",
    status: "In Progress",
    raisedBy: { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
    assignedTo: { id: "u6", name: "Rajan Tiwari", role: "Non-ULB Field Executive" },
    participants: [
      { id: "u4", name: "Muskan Agarwal", role: "Chartered Accountant" },
      { id: "u6", name: "Rajan Tiwari",   role: "Non-ULB Field Executive" },
    ],
    createdAt: "05/03/2026",
    dueDate: "13/03/2026",
    resolvedAt: null,
    daysTaken: null,
    attachments: [
      { name: "JMS_25Feb2026_unsigned.pdf", size: "124 KB", ext: "pdf" },
    ],
    replies: [
      {
        id: "r1",
        author: { id: "u6", name: "Rajan Tiwari", role: "Non-ULB Field Executive" },
        message:
          "I have coordinated with the ULB's office. The Junior Engineer was on field duty last week. He has reviewed the JMS and will sign it by 12th March. I will upload the signed copy immediately after.",
        createdAt: "07/03/2026 02:45 PM",
        attachments: [],
      },
    ],
    activityLog: [
      { id: "a1", type: "created",  actor: "Muskan Agarwal", at: "05/03/2026 04:00 PM", detail: null },
      { id: "a2", type: "assigned", actor: "Muskan Agarwal", at: "05/03/2026 04:01 PM", detail: "Assigned to Rajan Tiwari" },
      { id: "a3", type: "status",   actor: "Rajan Tiwari",   at: "06/03/2026 09:00 AM", detail: "Status changed to In Progress" },
      { id: "a4", type: "replied",  actor: "Rajan Tiwari",   at: "07/03/2026 02:45 PM", detail: null },
    ],
  },
];
